In [8]:
import numpy as np

In [9]:
a = np.array([10, 20, 30 ,40]).reshape(2, 2)
b = np.arange(4).reshape(2, 2)

In [10]:
print(a+b)

[[10 21]
 [32 43]]


In [11]:
c = 10 * np.tan(a)
print(c)

[[  6.48360827  22.37160944]
 [-64.05331197 -11.17214931]]


In [12]:
print(c<3)

[[False False]
 [ True  True]]


In [13]:
 print(a * b)

[[  0  20]
 [ 60 120]]


In [14]:
print(np.dot(a, b))

[[ 40  70]
 [ 80 150]]


In [17]:
a = np.random.random((2, 3))
print(a)

[[0.34138124 0.7264967  0.37216808]
 [0.93654196 0.76882838 0.3167726 ]]
